[[redirects]]
from = "/*"
to = "/index.html"
status = 200

from = "/*"
to = "/index.html/portfolio"
status = 200

from = "/*"
to = "/index.html/about"
status = 200

from = "/*"
to = "/index.html/contact"
status = 200